### ISSUE TITLE
Create boilerplate for creating services 

### ISSUE THREAD

**Issue by obengwilliam** [kudobuzz/express-api-starter#23]
At kudobuzzz we have a bunch of services working together to make sure our goals are achieved. To make it easy for  use to kick start new services we need to have a boilerplate that should contain our best practices, updated tools  and so on. 
Main Goals
Writing an application that is easy to scale and maintain.
The config is well separated from the business logic.
Our application can consist of multiple process types.

### Acceptance Criteria 
- [ ] - it should take advantage of some of things we have learnt over the years which we consider really good
- [ ] - it should use https://github.com/kudobuzz/kbscripts to provide a zero config boilerplate.
- [ ] - it should have some example code, a todo example might be cool
- [ ] - it should consider best practices from here https://github.com/i0natan/nodebestpractices
- [ ] - it should test example code using our testing strategies https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a 
- [ ]  - add health checks
- [ ] - Add logger https://github.com/kudobuzz/logger
- [ ] - it should follow https://12factor.net/
- [ ] - it should follow our api standards https://github.com/kudobuzz/api-standards
- [ ] - Add issue and pr templates

# Notes
There are quite a number of things that might not be here but this issue should be more of a 
discussion

### Tasks
 - [ ] - Create folder structure and add documentation for each folders #25 
-  [ ] - Add pr and issue templates
- [ ]  - Implement lint, test and precommit, prepush according to docs
