### ISSUE TITLE
Add boilerplate code to help new developers

### ISSUE THREAD

**Issue by obengwilliam** [kudobuzz/express-api-starter#29]
#### Issue Summary
We want to improve express-api-starter to contain all the information needed for new developers to quickly pick up how things are done here. 

#### Acceptance Criteria
 - [ ]  Document project structure
 - [ ]  Document how we handle test for api, workers or any concerns
 - [ ] Document api in openapi 3.0.0  
 - [ ] Include a client wrapper
- [ ] - Project Setup 
-[ ] - Implement a todo api the follows our api standards 
        - GEt /todos
        - POST  /todos
        - GET /todos/:todoid
- [ ] Include health route 
- [ ] Start resources properly using resource manager #
- [ ] Add autogeneration for basic things like 
       - Adding a new api
       - Adding a new processtype
      

#### Task
 - [ ]  Document project structure #30 
 - [ ]  Document how we handle test for api, workers or any concerns #31  
 - [ ] Document api in openapi 3.0.0  #32 
 - [ ] Include a client wrapper #36 
- [ ] - Project Setup #33 
- [ ] Include health route #34
